// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgdmyuuebueufenfluyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZG15dXVlYnVldWZlbmZsdXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjIzNjMsImV4cCI6MjA2NTMzODM2M30.JB8MY2z8yp6iH4s1vzfZu4daU0zMKNMqTFavPui3PvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
